version: '3.1'

services:
  api:
    container_name: api
    restart: always
    build: 
      context: ./back
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    ports: 
      - "8000:8000"
    networks:
      - native-adventur-network

  web:
    container_name: web
    restart: always
    build: 
      context: ./front
      dockerfile: Dockerfile
    ports: 
      - "3000:3000"
    depends_on:
      - api
    networks:
      - native-adventur-network

networks:
  native-adventur-network:
    driver: bridge