version: '3.1'

services:
  api_test:
    container_name: api_test
    restart: always
    build: 
      context: ./back
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8002
    ports: 
      - "8002:8002"
    networks:
      - test-native-adventure-network

  web_test:
    container_name: web_test
    restart: always
    build: 
      context: ./front
      dockerfile: Dockerfile
    ports: 
      - "3001:3001"
    depends_on:
      - api_test
    networks:
      - test-native-adventure-network

networks:
  test-native-adventure-network:
    driver: bridge