# Generated by Django 5.0.1 on 2024-01-12 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('firstTitle', models.CharField(max_length=255)),
                ('secondTitle', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('priority', models.IntegerField()),
                ('image', models.ImageField(upload_to='card_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Comentary',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('disabled', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('direccion', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('horario1', models.CharField(max_length=255)),
                ('horario2', models.CharField(max_length=255)),
                ('horario3', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DetailSection',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Excursion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('available', models.BooleanField()),
                ('duration', models.CharField(max_length=255)),
                ('quantity_people', models.IntegerField()),
                ('price', models.IntegerField()),
                ('image', models.ImageField(upload_to='excursion_images/')),
                ('description', models.TextField()),
                ('difficulty', models.CharField(max_length=255)),
                ('distance', models.CharField(max_length=255)),
                ('slope', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='section_images/')),
                ('icon', models.ImageField(upload_to='section_images/')),
                ('has_excursions', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='SectionImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ImagesExcursion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='excursion_images/')),
                ('excursion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.excursion')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('detail_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.detailsection')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mail', models.EmailField(max_length=254)),
                ('dni', models.CharField(max_length=255)),
                ('full_name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('date_of_birth', models.DateField()),
                ('nationality', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('accommodation', models.CharField(max_length=255)),
                ('reservation_date', models.DateField()),
                ('restriction_dietary', models.CharField(max_length=255)),
                ('menu', models.CharField(max_length=255)),
                ('excursion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.excursion')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalForm',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('emergency_contact', models.CharField(max_length=255)),
                ('health_insurance', models.CharField(max_length=255)),
                ('height', models.CharField(max_length=255)),
                ('weight', models.CharField(max_length=255)),
                ('hypertension', models.BooleanField()),
                ('diabetes', models.BooleanField()),
                ('allergic_reactions', models.BooleanField()),
                ('respiratory_diseases', models.BooleanField()),
                ('cardiovascular_diseases', models.BooleanField()),
                ('musculoskeletal_diseases', models.BooleanField()),
                ('phobia_or_fear', models.BooleanField()),
                ('smoking', models.BooleanField()),
                ('alcohol', models.BooleanField()),
                ('exercise_limitation', models.BooleanField()),
                ('other', models.BooleanField()),
                ('any_other_condition', models.CharField(max_length=255)),
                ('any_treatment', models.CharField(max_length=255)),
                ('surgical_procedure', models.CharField(max_length=255)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.reservation')),
            ],
        ),
        migrations.AddField(
            model_name='excursion',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.section'),
        ),
        migrations.AddField(
            model_name='detailsection',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.section'),
        ),
        migrations.CreateModel(
            name='SectionImageDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='section_images/')),
                ('section_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sectionimage')),
            ],
        ),
    ]
