# Generated by Django 5.0.1 on 2024-01-12 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='icon',
            field=models.FileField(upload_to='archivos_svg/'),
        ),
    ]
